/******** PK 15/07 Agregar columnas ********/
/******** PK 17/07 Agregar columna INFO_AUXILIAR ********/

USE [eFactura]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
BEGIN TRANSACTION
GO
ALTER TABLE [dbo].[EMPRESAS]
ADD  
[URL_AFIP_WSAA_FECRED] [varchar](500) NULL,
[URL_AFIP_WSFEv1_FECRED] [varchar](500) NULL,
[TICKET_EXPIRED_DATE_FECRED] [datetime] NULL,
[TICKET_TOKEN_FECRED] [ntext] NULL,
[TICKET_SIGN_FECRED] [ntext] NULL
GO
SELECT * FROM EMPRESAS
GO
COMMIT
GO
