/******** PK 17/07 Agregar columna INFO_AUXILIAR ********/
USE [eFactura]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
BEGIN TRANSACTION
GO
ALTER TABLE [dbo].[EMPRESAS]
ADD  
[INFO_AUXILIAR] [varchar](5000) NULL
GO
SELECT * FROM EMPRESAS
GO
COMMIT
GO
