USE [eFactura]
GO
/****** Object:  StoredProcedure [dbo].[TICKET_SET_FECRED]    Script Date: 16/7/2019 11:25:14 ******/
/****** PK 15/07 Nuevo SP para FECRED ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE procedure [dbo].[TICKET_SET_FECRED](
@EMPRESA_ID int,
@TICKET_EXPIRED_DATE_FECRED datetime,
@TICKET_TOKEN_FECRED ntext,
@TICKET_SIGN_FECRED ntext
)
AS 
	SET NOCOUNT ON
	UPDATE EMPRESAS
	SET
		TICKET_EXPIRED_DATE_FECRED = @TICKET_EXPIRED_DATE_FECRED, 
		TICKET_TOKEN_FECRED = @TICKET_TOKEN_FECRED,
		TICKET_SIGN_FECRED = @TICKET_SIGN_FECRED
	WHERE EMPRESA_ID = @EMPRESA_ID

GO


