USE [eFactura]
GO
INSERT [dbo].[secOPTIONS] ([MENU_NBR], [APPLICATION_NBR], [EN_OPTION_NM], [ES_OPTION_NM], [PT_OPTION_NM], [OPTION_TAG_TXT], [IS_PAGE_FG], [OPTION_URL_ADDR], [OPTION_ORDER_NBR], [USER_TYPE_CD]) VALUES (28, 11, N'Consulta CUIT', N'Consulta CUIT', NULL, N'EFACTURA_FRMCONSULTACUIT', 1, N'~\efactura\frmConsultaCUIT.aspx', 40, N'U')
GO