USE [eFactura]
GO
/****** Object:  StoredProcedure [dbo].[TICKET_GET_FECRED]    Script Date: 16/7/2019 11:22:42 ******/
/******** PK 15/07 SP NUEVO para FECRED ********/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE procedure [dbo].[TICKET_GET_FECRED](
@EMPRESA_ID int)
 as 
SET NOCOUNT ON

SELECT TICKET_EXPIRED_DATE_FECRED, TICKET_TOKEN_FECRED, TICKET_SIGN_FECRED
FROM EMPRESAS
WHERE EMPRESA_ID = @EMPRESA_ID

GO
