'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class frmCRUDLOGS

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''objMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objMenu As Global.ASF.WebControls.HelperMenu

    '''<summary>
    '''global_navigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents global_navigation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''side_navigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents side_navigation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''objCRUDToolBarHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objCRUDToolBarHeader As Global.ASF.WebControls.HelperCRUDToolBarHeader

    '''<summary>
    '''PanelSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelSearch As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbltxtLOG_ID_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltxtLOG_ID_SEARCH As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtLOG_ID_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLOG_ID_SEARCH As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lbltxtFECHA_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltxtFECHA_SEARCH As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtFECHA_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFECHA_SEARCH As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lbltxtTIPO_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltxtTIPO_SEARCH As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtTIPO_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTIPO_SEARCH As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lbltxtTEXTO_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltxtTEXTO_SEARCH As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtTEXTO_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTEXTO_SEARCH As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.ASF.WebControls.ButtonTyped

    '''<summary>
    '''btnClean control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClean As Global.ASF.WebControls.ButtonTyped

    '''<summary>
    '''dgrList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgrList As Global.ASF.WebControls.SearchResultsDataGrid

    '''<summary>
    '''PanelControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelControls As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblFECHA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFECHA As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtFECHA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFECHA As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblTIPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTIPO As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtTIPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTIPO As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblTEXTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTEXTO As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtTEXTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTEXTO As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''objWebDataBinder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objWebDataBinder As Global.ASF.WebControls.WebDataBinder

    '''<summary>
    '''objCRUDManagerHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objCRUDManagerHeader As Global.ASF.WebControls.CRUDManagerHeader
End Class
