'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class frmCRUDMAESTRO_Tributo

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''objMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objMenu As Global.ASF.WebControls.HelperMenu

    '''<summary>
    '''global_navigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents global_navigation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''side_navigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents side_navigation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''objCRUDToolBarHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objCRUDToolBarHeader As Global.ASF.WebControls.HelperCRUDToolBarHeader

    '''<summary>
    '''PanelSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelSearch As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbltxtCodigo_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltxtCodigo_SEARCH As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtCodigo_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodigo_SEARCH As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lbltxtDescripcion_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltxtDescripcion_SEARCH As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtDescripcion_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescripcion_SEARCH As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lbltxtCODIGO_ERP_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltxtCODIGO_ERP_SEARCH As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtCODIGO_ERP_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCODIGO_ERP_SEARCH As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.ASF.WebControls.ButtonTyped

    '''<summary>
    '''btnClean control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClean As Global.ASF.WebControls.ButtonTyped

    '''<summary>
    '''dgrList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgrList As Global.ASF.WebControls.SearchResultsDataGrid

    '''<summary>
    '''PanelControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelControls As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblDescripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescripcion As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtDescripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescripcion As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblCODIGO_ERP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCODIGO_ERP As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtCODIGO_ERP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCODIGO_ERP As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''objWebDataBinder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objWebDataBinder As Global.ASF.WebControls.WebDataBinder

    '''<summary>
    '''objCRUDManagerHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objCRUDManagerHeader As Global.ASF.WebControls.CRUDManagerHeader
End Class
