'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmCRUDDOCUMENTOS

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''objMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objMenu As Global.ASF.WebControls.HelperMenu

    '''<summary>
    '''global_navigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents global_navigation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''side_navigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents side_navigation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''objCRUDToolBarHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objCRUDToolBarHeader As Global.ASF.WebControls.HelperCRUDToolBarHeader

    '''<summary>
    '''PanelSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelSearch As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbltxtCbteFecha_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltxtCbteFecha_SEARCH As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtCbteFecha_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCbteFecha_SEARCH As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblcboESTADO_ID_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcboESTADO_ID_SEARCH As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''cboESTADO_ID_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboESTADO_ID_SEARCH As Global.ASF.WebControls.ComboBoxTyped

    '''<summary>
    '''lblcboCbteTipo_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcboCbteTipo_SEARCH As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''cboCbteTipo_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCbteTipo_SEARCH As Global.ASF.WebControls.ComboBoxTyped

    '''<summary>
    '''lbltxtPtoVta_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltxtPtoVta_SEARCH As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtPtoVta_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPtoVta_SEARCH As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lbltxtCbteNro_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltxtCbteNro_SEARCH As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtCbteNro_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCbteNro_SEARCH As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.ASF.WebControls.ButtonTyped

    '''<summary>
    '''btnClean control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClean As Global.ASF.WebControls.ButtonTyped

    '''<summary>
    '''dgrList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgrList As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''PanelControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelControls As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblEMPRESA_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEMPRESA_ID As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''cboEMPRESA_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboEMPRESA_ID As Global.ASF.WebControls.ComboBoxTyped

    '''<summary>
    '''lblCbteTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCbteTipo As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''cboCbteTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCbteTipo As Global.ASF.WebControls.ComboBoxTyped

    '''<summary>
    '''lblPtoVta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPtoVta As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtPtoVta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPtoVta As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblCbteNro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCbteNro As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtCbteNro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCbteNro As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblConcepto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConcepto As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtConcepto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConcepto As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblDocTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDocTipo As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''cboDocTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDocTipo As Global.ASF.WebControls.ComboBoxTyped

    '''<summary>
    '''lblDocNro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDocNro As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtDocNro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDocNro As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblImpTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImpTotal As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtImpTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpTotal As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblImpTotConc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImpTotConc As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtImpTotConc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpTotConc As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblImpNeto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImpNeto As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtImpNeto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpNeto As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblImpOpEx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImpOpEx As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtImpOpEx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpOpEx As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblImpIva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImpIva As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtImpIva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpIva As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblImpTrib control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImpTrib As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtImpTrib control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpTrib As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblCbteFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCbteFecha As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtCbteFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCbteFecha As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblFchServDesde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFchServDesde As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtFchServDesde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFchServDesde As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblFchServHasta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFchServHasta As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtFchServHasta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFchServHasta As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblFchVtoPago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFchVtoPago As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtFchVtoPago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFchVtoPago As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblMonId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonId As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''cboMonId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboMonId As Global.ASF.WebControls.ComboBoxTyped

    '''<summary>
    '''lblMonCotiz control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonCotiz As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtMonCotiz control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMonCotiz As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblESTADO_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblESTADO_ID As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''cboESTADO_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboESTADO_ID As Global.ASF.WebControls.ComboBoxTyped

    '''<summary>
    '''lblFECHA_ALTA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFECHA_ALTA As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtFECHA_ALTA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFECHA_ALTA As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblFECHA_ACTUALIZACION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFECHA_ACTUALIZACION As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtFECHA_ACTUALIZACION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFECHA_ACTUALIZACION As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblCAE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCAE As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtCAE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCAE As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblCAEFchVto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCAEFchVto As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtCAEFchVto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCAEFchVto As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtError As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblNOTAS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNOTAS As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtNOTAS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNOTAS As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''btnConsultar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConsultar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtRta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRta As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''objWebDataBinder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objWebDataBinder As Global.ASF.WebControls.WebDataBinder

    '''<summary>
    '''objCRUDManagerHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objCRUDManagerHeader As Global.ASF.WebControls.CRUDManagerHeader
End Class
