'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmCRUDEMPRESAS

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''objMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objMenu As Global.ASF.WebControls.HelperMenu

    '''<summary>
    '''global_navigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents global_navigation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''side_navigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents side_navigation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''objCRUDToolBarHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objCRUDToolBarHeader As Global.ASF.WebControls.HelperCRUDToolBarHeader

    '''<summary>
    '''dgrList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgrList As Global.ASF.WebControls.SearchResultsDataGrid

    '''<summary>
    '''PanelControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelControls As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCUIT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCUIT As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtCUIT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCUIT As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblPASSWORD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPASSWORD As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtPASSWORD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPASSWORD As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblRAZON_SOCIAL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRAZON_SOCIAL As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtRAZON_SOCIAL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRAZON_SOCIAL As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblURL_AFIP_WSAA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblURL_AFIP_WSAA As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtURL_AFIP_WSAA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtURL_AFIP_WSAA As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblURL_AFIP_WSFEv1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblURL_AFIP_WSFEv1 As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtURL_AFIP_WSFEv1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtURL_AFIP_WSFEv1 As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblRUTA_ARCHIVO_CERTIFICADO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRUTA_ARCHIVO_CERTIFICADO As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtRUTA_ARCHIVO_CERTIFICADO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRUTA_ARCHIVO_CERTIFICADO As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblEMAILS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEMAILS As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtEMAILS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEMAILS As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblTICKET_EXPIRED_DATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTICKET_EXPIRED_DATE As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtTICKET_EXPIRED_DATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTICKET_EXPIRED_DATE As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''LabelTyped1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTyped1 As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtURL_AFIP_WSAA_FECRED control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtURL_AFIP_WSAA_FECRED As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''LabelTyped2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTyped2 As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtURL_AFIP_WSFEv1_FECRED control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtURL_AFIP_WSFEv1_FECRED As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''LabelTyped3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTyped3 As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtTICKET_EXPIRED_DATE_FECRED control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTICKET_EXPIRED_DATE_FECRED As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblINFO_AUXILIAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblINFO_AUXILIAR As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtINFO_AUXILIAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtINFO_AUXILIAR As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lblCOMPROBANTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCOMPROBANTE As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtCUITEmisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCUITEmisor As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''LabelTIPOCMP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTIPOCMP As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtTIPOCMP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTIPOCMP As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''LabelPTOVTA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPTOVTA As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtPTOVTA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPTOVTA As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''LabelNROCMP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNROCMP As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtNROCMP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNROCMP As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''btnViewPOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewPOS As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnViewFCE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewFCE As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnViewJson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewJson As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnViewOpc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewOpc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnViewTiposCbte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewTiposCbte As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnViewTiposDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewTiposDoc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnViewTiposConcepto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewTiposConcepto As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnViewConsultaFCE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewConsultaFCE As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnViewComprobanteFCE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewComprobanteFCE As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnViewCtaCte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewCtaCte As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtRta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRta As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''objWebDataBinder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objWebDataBinder As Global.ASF.WebControls.WebDataBinder

    '''<summary>
    '''objCRUDManagerHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objCRUDManagerHeader As Global.ASF.WebControls.CRUDManagerHeader
End Class
