'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmCRUDMAESTRO_ESTADOS_DOCUMENTO

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''objMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objMenu As Global.ASF.WebControls.HelperMenu

    '''<summary>
    '''global_navigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents global_navigation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''side_navigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents side_navigation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''objCRUDToolBarHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objCRUDToolBarHeader As Global.ASF.WebControls.HelperCRUDToolBarHeader

    '''<summary>
    '''PanelSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelSearch As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbltxtESTADO_ID_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltxtESTADO_ID_SEARCH As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtESTADO_ID_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtESTADO_ID_SEARCH As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''lbltxtDESCRIPCION_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltxtDESCRIPCION_SEARCH As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtDESCRIPCION_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDESCRIPCION_SEARCH As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.ASF.WebControls.ButtonTyped

    '''<summary>
    '''btnClean control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClean As Global.ASF.WebControls.ButtonTyped

    '''<summary>
    '''dgrList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgrList As Global.ASF.WebControls.SearchResultsDataGrid

    '''<summary>
    '''PanelControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelControls As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblDESCRIPCION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDESCRIPCION As Global.ASF.WebControls.LabelTyped

    '''<summary>
    '''txtDESCRIPCION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDESCRIPCION As Global.ASF.WebControls.TextBoxTyped

    '''<summary>
    '''objWebDataBinder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objWebDataBinder As Global.ASF.WebControls.WebDataBinder

    '''<summary>
    '''objCRUDManagerHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objCRUDManagerHeader As Global.ASF.WebControls.CRUDManagerHeader
End Class
